WITH
  T0 AS (
    SELECT DISTINCT
      PORDERP.PRHFCY_0,
      PORDERP.POHNUM_0,
      PORDERP.POPLIN_0,
      PORDERP.PJT_0,
      PORDERP.ITMREF_0,
      RTRIM (
        PORDERP.ITMDES1_0 + ' ' + PORDERP.ITMDES2_0 + ' ' + PORDERP.ITMDES3_0
      ) AS Description,
      PORDERQ.QTYSTU_0,
      PORDERQ.LINATIAMT_0,
      PORDERQ.NETCUR_0,
      PORDERP.CREDAT_0,
      PORDERP.CREUSR_0,
      AUTILIS.ADDEML_0
    FROM
      EXPLOIT.PORDERP AS PORDERP
      INNER JOIN EXPLOIT.PORDERQ AS PORDERQ ON PORDERP.POHNUM_0 = PORDERQ.POHNUM_0
      AND PORDERP.POPLIN_0 = PORDERQ.POPLIN_0
      LEFT JOIN EXPLOIT.AUTILIS AUTILIS ON AUTILIS.USR_0 = PORDERP.CREUSR_0
    WHERE
      PORDERP.PRHFCY_0 = '#{Site}'
      AND PORDERQ.LINCLEFLG_0 = 1 --- line open flag, exclude manual closed(value=2) po line
      AND PORDERP.NETPRI_0 > 0 --- exclude manually mark 0, it's an error line
      AND SUBSTRING(PORDERP.POHNUM_0, 2, 2) != 'CT' --- exclude delivery
      ---FACHDIV0001:   PURCHASE VARIOUS
      ---FACHTRADRTD:   INBOUND CUSTOM FEES
      ---FVENTRAAUT:    OUTBOUND SHIPMENT FEES
      ---FACHTRAAUT:    INBOUND SHIPMENT FEES
      AND PORDERP.ITMREF_0 NOT IN (
        'FACHDIV0001',
        'FACHTRADRTD',
        'FVENTRAAUT',
        'FACHTRAAUT'
      )
  ),
  T1 AS (
    SELECT DISTINCT
      PRECEIPTD.POHNUM_0,
      PRECEIPTD.POPLIN_0
    FROM
      EXPLOIT.PRECEIPTD AS PRECEIPTD
    WHERE
      PRECEIPTD.PRHFCY_0 = '#{Site}'
  ),
  T2 AS (
    SELECT
      T0.PRHFCY_0 AS Site,
      T0.POHNUM_0 AS PurchaseNO,
      T0.POPLIN_0 AS PurchaseLine,
      T0.PJT_0 AS ProjectNO,
      T0.ITMREF_0 AS PurchasePN,
      T0.Description,
      T0.QTYSTU_0 AS PurchaseQty,
      T0.LINATIAMT_0 AS PurchaseAmount,
      T0.NETCUR_0 AS PurchaseCurrency,
      T0.CREDAT_0 AS PurchaseDate,
      T0.CREUSR_0 AS Purchaser,
      T0.ADDEML_0 AS PurchaserEmail
    FROM
      T0
      LEFT JOIN T1 ON T1.POHNUM_0 = T0.POHNUM_0
      AND T1.POPLIN_0 = T0.POPLIN_0
    WHERE
      T1.POHNUM_0 IS NULL
      AND T1.POPLIN_0 IS NULL
  )
SELECT DISTINCT
  T2.Site,
  T2.PurchaseNO,
  T2.PurchaseLine,
  T2.PurchasePN,
  T2.Description,
  T2.PurchaseQty,
  T2.PurchaseAmount,
  T2.PurchaseCurrency,
  T2.PurchaserEmail,
  T2.PurchaseDate,
  T2.Purchaser,
  T2.ProjectNO,
  SINVOICED.NUM_0 AS InvoiceNO,
  SINVOICED.INVDAT_0 AS InvoiceDate
FROM
  T2
  INNER JOIN EXPLOIT.SINVOICED SINVOICED ON SINVOICED.YSOH_PJT_0 = T2.ProjectNO
  AND SINVOICED.SALFCY_0 = T2.Site
  INNER JOIN EXPLOIT.SINVOICEV SINVOICEV ON SINVOICED.NUM_0 = SINVOICEV.NUM_0
  AND SINVOICEV.SIVTYP_0 = 'FFC' -- ONLY FFC
