SELECT DISTINCT 
  IIF(SORDERQ.YSOQ_PJTORI_0='',SORDERQ.YSOH_PJT_0,SORDERQ.YSOQ_PJTORI_0) AS ProjectNO,
  SORDERP.SOHNUM_0 AS SalesOrderNO,
  SORDER.SOHTYP_0 AS OrderType,
  SORDERP.ITMREF_0 AS PN,
  RTRIM(SORDERP.ITMDES1_0 +' '+ SORDERP.ITMDES2_0 +' '+ SORDERP.ITMDES3_0) AS Description,
  SORDERQ.QTY_0 AS QTY,
  SORDERP.SAU_0 AS Unit,
  SORDERP.NETPRIATI_0 AS OrderPrice,
  SORDER.CUR_0 AS OrderCurrency,  
  SORDERQ.YSOQ_MARK_0 AS Mark,
  SORDERQ.YSOQ_PAINT_0 AS Paint,
  SORDER.BPCORD_0 AS CustomerCode,
  SORDER.BPCNAM_0 AS CustomerName,
  SORDERQ.ORDDAT_0 AS OrderDate,
  SORDERQ.DEMDLVDAT_0 AS DemandDate,
  CASE
    WHEN SORDERQ.YSOQ_STA_0 =1 THEN SORDER.SOHTYP_0 + '-Methods'
    WHEN SORDERQ.YSOQ_STA_0 =2 THEN SORDER.SOHTYP_0 + '-InteralProd'
    WHEN SORDERQ.YSOQ_STA_0 =3 THEN SORDER.SOHTYP_0 + '-ExternalProd'
    WHEN SORDERQ.YSOQ_STA_0 =4 THEN SORDER.SOHTYP_0 + '-Design'
    WHEN SORDERQ.YSOQ_STA_0 =5 THEN SORDER.SOHTYP_0 + '-Stock'
    WHEN SORDERQ.YSOQ_STA_0 =6 THEN SORDER.SOHTYP_0 + '-Trading'
    WHEN SORDERQ.YSOQ_STA_0 =7 THEN SORDER.SOHTYP_0 + '-Services'
    WHEN SORDERQ.YSOQ_STA_0 =8 THEN SORDER.SOHTYP_0 + '-SalesAdmin'
    ELSE SORDER.SOHTYP_0 + '-UNK' END AS OrderStatus,
  SORDERQ.YWR_STA_0 AS ProjectStatusCode,
  CASE
    WHEN SORDERQ.YWR_STA_0 =0 THEN ''
    WHEN SORDERQ.YWR_STA_0 =1 THEN 'In hold'
    WHEN SORDERQ.YWR_STA_0 =2 THEN 'In progress'
    WHEN SORDERQ.YWR_STA_0 =3 THEN 'PO Cancelled'
    WHEN SORDERQ.YWR_STA_0 =4 THEN 'Delivered'
    WHEN SORDERQ.YWR_STA_0 =5 THEN 'Customer StandBy'
    ELSE 'UNK' END AS ProjectStatus,
  SORDERQ.YWR_CBLOC_0 AS ProjectBlockReasonCode,
	CASE
    WHEN SORDERQ.YWR_CBLOC_0 =0 THEN ''
    WHEN SORDERQ.YWR_CBLOC_0 =1 THEN '-'
    WHEN SORDERQ.YWR_CBLOC_0 =2 THEN 'AMENDMENT'
    WHEN SORDERQ.YWR_CBLOC_0 =3 THEN 'PAYMENT'
    WHEN SORDERQ.YWR_CBLOC_0 =4 THEN 'TECHNICAL DATA'
    WHEN SORDERQ.YWR_CBLOC_0 =5 THEN 'DEVIATION REQUEST'
    WHEN SORDERQ.YWR_CBLOC_0 =6 THEN 'QUALIFICATION'
    WHEN SORDERQ.YWR_CBLOC_0 =7 THEN 'WAITING TOOL'
    ELSE 'UNK' END AS ProjectBlockReason,
  RTRIM(LTRIM(SORDERQ.YWR_COM_0)) AS ProjectComment,
  RTRIM(LTRIM(SORDERQ.YWR_ACT_0)) AS ProjectAction,
  DATEDIFF(DAY, SORDERQ.ORDDAT_0, GETDATE()) AS DaysCount,
  DATEDIFF(DAY, GETDATE(), SORDERQ.DEMDLVDAT_0) AS DaysLeft
FROM EXPLOIT.SORDERP AS SORDERP
INNER JOIN EXPLOIT.SORDERQ AS SORDERQ
  ON SORDERP.SOHNUM_0 = SORDERQ.SOHNUM_0
    AND SORDERP.SOPLIN_0 = SORDERQ.SOPLIN_0
    AND SORDERP.SALFCY_0 = '#{Site}'
    AND SORDERQ.SALFCY_0 = '#{Site}'
    AND SORDERQ.ORDDAT_0 <= DATEADD(DAY, -1 * #{Days}, GETDATE())    ---- add diffDays
    AND SORDERQ.SOQSTA_0 != 3     --- open status only
    AND SORDERQ.YWR_STA_0 IN (0,2)  --- only 'In progress' and not select
INNER JOIN EXPLOIT.SORDER AS SORDER
  ON SORDERP.SOHNUM_0 = SORDER.SOHNUM_0
    AND SORDER.SALFCY_0 = '#{Site}'
LEFT JOIN EXPLOIT.MFGITM MFGITM
  ON MFGITM.PJT_0 = SORDERQ.YSOH_PJT_0
     AND MFGITM.MFGFCY_0 = '#{Site}'
  LEFT JOIN EXPLOIT.MFGITM MFGITM2
    ON MFGITM2.PJT_0 = SORDERQ.YSOQ_PJTORI_0
     AND MFGITM2.MFGFCY_0 = '#{Site}'
     AND SORDERQ.YSOQ_PJTORI_0 !=''
LEFT JOIN EXPLOIT.PORDERP PORDERP
     ON PORDERP.PJT_0 = SORDERQ.YSOH_PJT_0
        AND PORDERP.PRHFCY_0 = '#{Site}'
LEFT JOIN EXPLOIT.PORDERP PORDERP2
     ON PORDERP2.PJT_0 = SORDERQ.YSOQ_PJTORI_0
        AND PORDERP2.PRHFCY_0 = '#{Site}'
      AND SORDERQ.YSOQ_PJTORI_0 !=''
WHERE
  MFGITM.MFGNUM_0 IS NULL
  AND PORDERP.POHNUM_0 IS NULL
  AND MFGITM2.MFGNUM_0 IS NULL
  AND PORDERP2.POHNUM_0 IS NULL
ORDER BY SORDERQ.ORDDAT_0 ASC