    SELECT DISTINCT
      PORDERP.POHNUM_0 AS PurchaseNO,
      PORDERP.POPLIN_0 AS Line,
      PORDERP.PJT_0 AS ProjectNO,
      PORDERP.ITMREF_0 AS PN,
      PORDERP.ITMDES_0 AS Description,
      PORDER.CUR_0 AS Currency,
      PORDERP.NETPRI_0 AS NetPrice,
      PORDERQ.QTYPUU_0 AS QTY,
      PORDERQ.PUU_0 AS Unit,
      PORDER.BPSNUM_0 AS VendorCode,
      PORDER.BPRNAM_0 AS VendorName,
      IIF(PORDERQ.LINOCNDAT_0='1753-01-01', PORDERQ.EXTRCPDAT_0, PORDERQ.LINOCNDAT_0) AS AckDate,
      PORDERQ.EXTRCPDAT_0 AS ExpectDate,
      PORDER.ORDDAT_0 AS OrderDate,
      PORDER.CREUSR_0 AS CreateUser
    FROM  EXPLOIT.PORDERP AS PORDERP
    INNER JOIN EXPLOIT.PORDERQ AS PORDERQ
      ON PORDERP.POHNUM_0=PORDERQ.POHNUM_0
        AND PORDERP.POPLIN_0=PORDERQ.POPLIN_0
        AND PORDERQ.PRHFCY_0 = #{Site}
        AND PORDERP.PRHFCY_0 = #{Site}
        AND PORDERQ.LINCLEFLG_0 != 2
        AND PORDERQ.EXTRCPDAT_0 &lt;  GETDATE()   --- after ExpectDate
    INNER JOIN EXPLOIT.PORDER AS PORDER
      ON PORDERP.POHNUM_0=PORDER.POHNUM_0
          AND PORDER.ORDDAT_0 &gt;= DATEADD(day, #{DiffDaysStart}, GETDATE())    --- add diffDays
          AND PORDER.ORDDAT_0 &lt; DATEADD(day, #{DiffDaysEnd}, GETDATE())    --- add diffDays
        AND PORDER.POHFCY_0 = #{Site}
    ORDER BY PORDERQ.EXTRCPDAT_0 ASC