  SELECT DISTINCT
      IIF(SORDERQ.YSOQ_PJTORI_0='',SORDERQ.YSOH_PJT_0,SORDERQ.YSOQ_PJTORI_0) AS ProjectNO,
      SORDERQ.SOHNUM_0 AS OrderNO,
      (CASE WHEN SORDERQ.YSOQ_STA_0 =1 THEN SORDER.SOHTYP_0 + '-Methods'
      WHEN SORDERQ.YSOQ_STA_0 =2 THEN SORDER.SOHTYP_0 + '-InteralProd'
      WHEN SORDERQ.YSOQ_STA_0 =3 THEN SORDER.SOHTYP_0 + '-ExternalProd'
      WHEN SORDERQ.YSOQ_STA_0 =4 THEN SORDER.SOHTYP_0 + '-Design'
      WHEN SORDERQ.YSOQ_STA_0 =5 THEN SORDER.SOHTYP_0 + '-Stock'
      WHEN SORDERQ.YSOQ_STA_0 =6 THEN SORDER.SOHTYP_0 + '-Trading'
      WHEN SORDERQ.YSOQ_STA_0 =7 THEN SORDER.SOHTYP_0 + '-Services'
      WHEN SORDERQ.YSOQ_STA_0 =8 THEN SORDER.SOHTYP_0 + '-SalesAdmin'
      ELSE SORDER.SOHTYP_0 + '-UNK' END) AS OrderType,
      SORDERP.ITMREF_0 AS PN,
      SORDERP.ITMDES_0 AS Description,
      SORDERQ.QTY_0 AS QTY,
      SORDERP.NETPRI_0 AS NetPrice,
      SORDER.CUR_0 AS Currency,
      SORDER.BPCORD_0 AS CustomerCode,
      SORDER.BPCNAM_0 AS CustomerName,
      SORDER.ORDDAT_0 AS OrderDate,
      SORDERQ.DEMDLVDAT_0 AS RequestDate,
      SORDERQ.YSOQ_DLIVP_0 AS PlanedDate
    FROM EXPLOIT.SORDERQ AS SORDERQ
    INNER JOIN EXPLOIT.SORDERP AS SORDERP
      ON SORDERP.SOHNUM_0 = SORDERQ.SOHNUM_0
        AND SORDERP.SOPLIN_0 = SORDERQ.SOPLIN_0
        AND SORDERQ.SALFCY_0 = '#{Site}'
        AND SORDERP.SALFCY_0 = '#{Site}'
        AND SORDERQ.SOQSTA_0 != 3
    INNER JOIN EXPLOIT.SORDER SORDER
      ON SORDERP.SOHNUM_0 = SORDER.SOHNUM_0
          AND SORDER.SALFCY_0 = '#{Site}'
          AND SORDER.SOHTYP_0 != 'LOC'
    WHERE
      SORDERQ.DEMDLVDAT_0 >= DATEADD(day, #{DiffDaysStart}, GETDATE())    ---- add diffDays
      AND SORDERQ.DEMDLVDAT_0 >= DATEADD(day, #{DiffDaysEnd}, GETDATE())    ---- add diffDays
    ORDER BY SORDERQ.DEMDLVDAT_0 ASC