  SELECT
      PRECEIPTD.POHNUM_0 AS PurchaseNO,
      PRECEIPTD.POPLIN_0 AS PurchaseLine,
      PORDERP.CREDAT_0 AS PurchaseDate,
      PORDERP.CREUSR_0 AS Purchaser,
      PRECEIPTD.PJT_0 AS ProjectNO,
      PRECEIPTD.ITMREF_0 AS PN,
      PRECEIPTD.ITMDES1_0 + PRECEIPTD.ITMDES2_0 AS Description,
      PRECEIPTD.QTYSTU_0 AS Qty,
      PRECEIPTD.STU_0 AS Unit,
      PRECEIPTD.CPRPRI_0 AS Price,
      PRECEIPTD.CPRCUR_0 AS Currency,
      PRECEIPTD.PTHNUM_0 AS ReceiveNO,
      PRECEIPTD.PTDLIN_0 AS ReceiveLine,
      PRECEIPTD.RCPDAT_0 AS ReceiveDate,
      PRECEIPTD.CREUSR_0 AS Receiptor,
      PRECEIPT.BPSNUM_0 AS VendorCode,
      PRECEIPT.BPONAM_0 AS VendorName
    FROM EXPLOIT.PRECEIPTD PRECEIPTD
        INNER JOIN EXPLOIT.PRECEIPT PRECEIPT
          ON PRECEIPT.PTHNUM_0 = PRECEIPTD.PTHNUM_0
        INNER JOIN EXPLOIT.PORDERP PORDERP
          ON PRECEIPTD.POHNUM_0 =PORDERP.POHNUM_0 AND PRECEIPTD.POPLIN_0 = PORDERP.POPLIN_0
    WHERE PRECEIPTD.LININVFLG_0 = 1
      AND PRECEIPTD.YPTD_NC_0 != 1                                      --- exclude manual marked nc
      AND LEFT(PRECEIPTD.ITMREF_0,4) != 'PNOG'                          --- exclude PNOG
      AND PRECEIPTD.RCPDAT_0 &gt;=  DATEADD(DAY, #{DiffDaysStart}, GETDATE())
      AND PRECEIPTD.RCPDAT_0 &lt;  DATEADD(DAY, #{DiffDaysEnd}, GETDATE())
      AND PRECEIPTD.PRHFCY_0 = #{Site}
    ORDER BY PRECEIPTD.RCPDAT_0 ASC