  --- Only open po line
   WITH
    T0 AS (  -- find open PO of zhuhai
      SELECT DISTINCT
        PORDERP.PJT_0
      FROM
        EXPLOIT.PORDERP PORDERP
      INNER JOIN EXPLOIT.PORDERQ AS PORDERQ
        ON PORDERP.POHNUM_0=PORDERQ.POHNUM_0
            AND PORDERP.POPLIN_0=PORDERQ.POPLIN_0
            AND PORDERQ.LINCLEFLG_0 != 2
      WHERE
        PORDERP.PRHFCY_0 = 'ZHU'
    ),
    T1 AS (  -- find open PO of shanghai
    SELECT DISTINCT
        PORDERP.PJT_0
      FROM
        EXPLOIT.PORDERP PORDERP
      INNER JOIN EXPLOIT.PORDERQ AS PORDERQ
        ON PORDERP.POHNUM_0=PORDERQ.POHNUM_0
            AND PORDERP.POPLIN_0=PORDERQ.POPLIN_0
            AND PORDERQ.LINCLEFLG_0 != 2
      WHERE
        PORDERP.PRHFCY_0 = 'YSH'
    ),
    T2 AS (
      SELECT DISTINCT
        PORDERP.PJT_0
      FROM
        EXPLOIT.PORDERP PORDERP
      WHERE
        PORDERP.PRHFCY_0 = 'ZHU'
    ),
    T3 AS (
      SELECT DISTINCT
        PORDERP.PJT_0
      FROM
        EXPLOIT.PORDERP PORDERP
      WHERE
        PORDERP.PRHFCY_0 = 'YSH'
    ),
    T4 AS (
     SELECT DISTINCT
        T0.PJT_0
     FROM T0
     INNER JOIN T3
       ON T0.PJT_0 = T3.PJT_0

     UNION

     SELECT DISTINCT
        T1.PJT_0
     FROM T1
     INNER JOIN T2
       ON T1.PJT_0 = T2.PJT_0
    ),
    T5 AS (
    SELECT
      PORDERP.PJT_0,
      PORDERP.PRHFCY_0,
      PORDERP.POHNUM_0,
      PORDERP.POPLIN_0,
      PORDERP.ITMREF_0,
      PORDERP.CREUSR_0,      
      AUTILIS.ADDEML_0,
      PORDERP.CREDAT_0
    FROM T4
    INNER JOIN EXPLOIT.PORDERP PORDERP
        ON  T4.PJT_0 = PORDERP.PJT_0
            AND LEFT(PORDERP.PRHFCY_0,1) != LEFT(PORDERP.PJT_0,1)
    INNER JOIN EXPLOIT.PORDERQ AS PORDERQ
        ON PORDERP.POHNUM_0=PORDERQ.POHNUM_0
            AND PORDERP.POPLIN_0=PORDERQ.POPLIN_0
            AND PORDERQ.LINCLEFLG_0 != 2
            AND (PORDERP.PRHFCY_0 = 'ZHU' OR PORDERP.PRHFCY_0 = 'YSH')  
    LEFT JOIN EXPLOIT.AUTILIS AUTILIS
        ON AUTILIS.USR_0 = PORDERP.CREUSR_0
    )

    SELECT
      T5.PJT_0 AS ProjectNO,
      T5.POHNUM_0 AS PurchaseNO,
      T5.POPLIN_0 AS PurchaseLine,
      T5.ITMREF_0 AS PN,
      T5.CREUSR_0 AS CreateUser,
      T5.ADDEML_0 AS CreateUserEmail,
      T5.CREDAT_0 AS CreateDate
    FROM T5