WITH
  T0 AS (
    SELECT DISTINCT
    MFGITM.PJT_0
    FROM
    EXPLOIT.MFGITM AS MFGITM
    WHERE
    MFGITM.MFGFCY_0 = 'ZHU'
  ),
  T1 AS (
  SELECT DISTINCT
    MFGITM.PJT_0
    FROM
    EXPLOIT.MFGITM AS MFGITM
    WHERE
    MFGITM.MFGFCY_0 = 'YSH'
  ),
  T2 AS (
  SELECT DISTINCT
    T0.PJT_0
    FROM
    T0
    INNER JOIN T1
    ON T0.PJT_0 = T1.PJT_0
  )

  SELECT
     MFGITM.PJT_0 AS ProjectNO,
     MFGITM.ITMREF_0 AS PN,
     MFGITM.MFGNUM_0 AS WO,
     MFGITM.CREUSR_0 AS CreateUser,
     AUTILIS.ADDEML_0 AS CreateUserEmail,
     MFGITM.CREDAT_0 AS CreateDate
  FROM 
     EXPLOIT.MFGITM AS MFGITM
  LEFT JOIN EXPLOIT.AUTILIS AUTILIS
      ON AUTILIS.USR_0 = MFGITM.CREUSR_0
  INNER JOIN T2
         ON MFGITM.PJT_0 = T2.PJT_0
         AND MFGITM.ITMSTA_0 != 3