SELECT DISTINCT
  SORDERP.SOHNUM_0 AS SalesOrderNO,
  SORDER.SOHTYP_0 AS OrderType,
  SORDERP.ITMREF_0 AS PN,
  SORDERP.ITMDES_0 AS Description,
  SORDERQ.QTY_0 AS QTY,
  SORDERP.SAU_0 AS Unit,
  SORDER.BPCORD_0 AS CustomerCode,
  SORDER.BPCNAM_0 AS CustomerName,
  SORDERQ.ORDDAT_0 AS OrderDate,
  SORDERQ.DEMDLVDAT_0 AS DemandDate,
  IIF(SORDERQ.YSOQ_PJTORI_0='',SORDERQ.YSOH_PJT_0,SORDERQ.YSOQ_PJTORI_0) AS ProjectNO,
  (CASE WHEN SORDERQ.YSOQ_STA_0 =1 THEN 'Methods'
  WHEN SORDERQ.YSOQ_STA_0 =2 THEN 'InteralProd'
  WHEN SORDERQ.YSOQ_STA_0 =3 THEN 'ExternalProd'
  WHEN SORDERQ.YSOQ_STA_0 =4 THEN 'Design'
  WHEN SORDERQ.YSOQ_STA_0 =5 THEN 'Stock'
  WHEN SORDERQ.YSOQ_STA_0 =6 THEN 'Trading'
  WHEN SORDERQ.YSOQ_STA_0 =7 THEN 'Services'
  WHEN SORDERQ.YSOQ_STA_0 =8 THEN 'SalesAdmin'
  ELSE 'UNK' END) AS OrderCategory
FROM EXPLOIT.SORDERP AS SORDERP
INNER JOIN EXPLOIT.SORDERQ AS SORDERQ
  ON SORDERP.SOHNUM_0 = SORDERQ.SOHNUM_0
    AND SORDERP.SOPLIN_0 = SORDERQ.SOPLIN_0
    AND SORDERP.SALFCY_0 = '#{Site}'
    AND SORDERQ.SALFCY_0 = '#{Site}'
    AND SORDERQ.SOQSTA_0 != 3
    AND SORDERQ.SOQSTA_0 != 8
INNER JOIN EXPLOIT.SORDER AS SORDER
  ON SORDERP.SOHNUM_0 = SORDER.SOHNUM_0
    AND SORDER.SALFCY_0 = '#{Site}'
LEFT JOIN EXPLOIT.MFGITM MFGITM
  ON MFGITM.PJT_0 = SORDERQ.YSOH_PJT_0
     AND MFGITM.MFGFCY_0 = '#{Site}'
  LEFT JOIN EXPLOIT.MFGITM MFGITM2
    ON MFGITM2.PJT_0 = SORDERQ.YSOQ_PJTORI_0
     AND MFGITM2.MFGFCY_0 = '#{Site}'
     AND SORDERQ.YSOQ_PJTORI_0 !=''
WHERE
  MFGITM.MFGNUM_0 IS NULL
  AND MFGITM2.MFGNUM_0 IS NULL
        AND SORDERP.SALFCY_0 != 'HKG'                    ---- Not HKG
        AND SORDERQ.YSOQ_STA_0 =7                              ---- Services only
        AND SUBSTRING(SORDERQ.YSOH_PJT_0,2,4) = 'DSRP'         ---- DSRP only
ORDER BY SORDERQ.ORDDAT_0 ASC