    SELECT DISTINCT
      MFGITM.PJT_0 AS ProjectNO,
      SORDER.SOHTYP_0 AS OrderType,
      SORDER.BPCORD_0 AS CustomerCode,
      SORDER.BPCNAM_0 AS CustomerName,
      MFGITM.ITMREF_0 AS ForPN,
      MFGMAT.MFGNUM_0 AS WorkOrderNO,
      MFGMAT.BOMSEQ_0 AS BomSeq,
      MFGMAT.ITMREF_0 AS PN,
      CONCAT(ITMMASTER.ITMDES1_0,ITMMASTER.ITMDES2_0,ITMMASTER.ITMDES3_0) AS Description,
      MFGMAT.RETQTY_0 AS QTY,
      MFGMAT.BOMUOM_0 AS Unit,
      MFGMAT.SHTQTY_0 AS ShortQty,
      MFGMAT.ALLQTY_0 AS AllQty,
      MFGMAT.CREDAT_0 AS CreateDate
    FROM EXPLOIT.MFGMAT AS MFGMAT
    INNER JOIN EXPLOIT.MFGITM AS MFGITM
         ON MFGITM.MFGNUM_0 = MFGMAT.MFGNUM_0
          AND MFGITM.MFGLIN_0 = MFGMAT.MFGLIN_0
          AND MFGMAT.SHTQTY_0 &gt; 0
          AND MFGMAT.CREDATTIM_0 &gt;= DATEADD(day, #{DiffDaysStart}, GETDATE())    ---- add diffDays
          AND MFGMAT.CREDATTIM_0 &lt; DATEADD(day, #{DiffDaysEnd}, GETDATE())    ---- add diffDays
          AND MFGITM.MFGFCY_0 = #{Site}
          AND MFGMAT.MFGFCY_0 = #{Site}
    LEFT JOIN EXPLOIT.ITMMASTER AS ITMMASTER
         ON MFGMAT.ITMREF_0 = ITMMASTER.ITMREF_0
    LEFT JOIN EXPLOIT.SORDERQ AS SORDERQ
         ON SORDERQ.YSOH_PJT_0 = MFGITM.PJT_0
         AND SORDERQ.SALFCY_0 = #{Site}
    LEFT JOIN EXPLOIT.SORDER AS SORDER
         ON SORDERQ.SOHNUM_0 = SORDER.SOHNUM_0
         AND SORDER.SALFCY_0  = #{Site}
    LEFT JOIN EXPLOIT.PORDERP AS PORDERP
          ON PORDERP.PJT_0 = MFGITM.PJT_0
          AND PORDERP.ITMREF_0 = MFGMAT.ITMREF_0
          AND PORDERP.PRHFCY_0 = #{Site}
    WHERE  PORDERP.POHNUM_0 IS NULL
    ORDER BY MFGMAT.CREDAT_0  ASC