WITH T0 AS (
    SELECT DISTINCT
      PORDERP.POHNUM_0 AS OrderNO,
      PORDERP.POPLIN_0 AS Line,
      PORDERP.PJT_0 AS ProjectNO,
      PORDERP.ITMREF_0 AS PN
    FROM  EXPLOIT.PORDERP AS PORDERP
    INNER JOIN EXPLOIT.PORDERQ AS PORDERQ
      ON PORDERP.POHNUM_0=PORDERQ.POHNUM_0
        AND PORDERP.POPLIN_0=PORDERQ.POPLIN_0
        AND PORDERQ.PRHFCY_0 = '#{Site}'
        AND PORDERP.PRHFCY_0 = '#{Site}'
        AND PORDERQ.LINCLEFLG_0 != 2  --- open status only

    UNION

  SELECT DISTINCT 
    SORDERP.SOHNUM_0 AS OrderNO,
    SORDERP.SOPLIN_0 AS Line,
    SORDERQ.YSOH_PJT_0 AS ProjectNO,
    SORDERP.ITMREF_0 AS PN
  FROM EXPLOIT.SORDERP AS SORDERP
  INNER JOIN EXPLOIT.SORDERQ AS SORDERQ
    ON SORDERP.SOHNUM_0 = SORDERQ.SOHNUM_0
      AND SORDERP.SOPLIN_0 = SORDERQ.SOPLIN_0
      AND SORDERP.SALFCY_0 = '#{Site}'
      AND SORDERQ.SALFCY_0 = '#{Site}'
      AND SORDERQ.SOQSTA_0 != 3     --- open status only
)

SELECT T0.*,
  ITMMASTER.TSICOD_0 AS Category,
  RTRIM(ITMMASTER.ITMDES1_0 +' '+ ITMMASTER.ITMDES2_0 +' '+ ITMMASTER.ITMDES3_0) AS Description,
  CASE 
    WHEN ITMMASTER.LOTMGTCOD_0 =1 THEN 'Not Managed'
    WHEN ITMMASTER.LOTMGTCOD_0 =2 THEN 'Optimal Managed'
    WHEN ITMMASTER.LOTMGTCOD_0 =3 THEN 'Mandatory Managed'
    WHEN ITMMASTER.LOTMGTCOD_0 =4 THEN 'Lot and Sublot Managed'
    ELSE 'UNK' END AS LotManage,
  CASE 
    WHEN ITMMASTER.SERMGTCOD_0 =1 THEN 'Not Managed'
    WHEN ITMMASTER.SERMGTCOD_0 =2 THEN 'Issued Managed'
    WHEN ITMMASTER.SERMGTCOD_0 =3 THEN 'Received/Issued Managed'
    WHEN ITMMASTER.SERMGTCOD_0 =4 THEN 'Global Received/Issued Managed'
    ELSE 'UNK' END AS SerialManage,
  CASE 
    WHEN ITMMASTER.STOMGTCOD_0 =1 THEN 'Not Managed'
    WHEN ITMMASTER.STOMGTCOD_0 =2 THEN 'Managed'
    WHEN ITMMASTER.STOMGTCOD_0 =3 THEN 'Potency Managed'
    ELSE 'UNK' END AS StockManage,
  ITMMASTER.UPDUSR_0 AS UpdateUser,
  ITMMASTER.UPDDAT_0 AS UpdateDate,
  AUTILIS.ADDEML_0 AS Email
FROM T0
INNER JOIN EXPLOIT.ITMMASTER AS ITMMASTER
  ON T0.PN = ITMMASTER.ITMREF_0
  LEFT JOIN EXPLOIT.AUTILIS AUTILIS
      ON AUTILIS.USR_0 = ITMMASTER.UPDUSR_0
WHERE
  --- Not Stock managed
  (ITMMASTER.STOMGTCOD_0 = 1 AND ITMMASTER.TSICOD_0 NOT IN ('F0001','F0002','F0003','F0004'))
  --- Serial managed must lot managed
  OR (ITMMASTER.LOTMGTCOD_0 = 1 AND ITMMASTER.SERMGTCOD_0 != 1)
  --- Service PN P0003 should not lot and serial
  -- OR (ITMMASTER.TSICOD_0 = 'P0003' AND ITMMASTER.LOTMGTCOD_0 != 1)
  OR (ITMMASTER.TSICOD_0 = 'P0003' AND ITMMASTER.SERMGTCOD_0 != 1)
  --- Other PN Pxxxx should lot and serial  
  --OR (ITMMASTER.TSICOD_0 IN ('P0001','P0002','P0004','P0006') AND ITMMASTER.LOTMGTCOD_0 = 1)
  --OR (ITMMASTER.TSICOD_0 IN ('P0001','P0002','P0004','P0006') AND ITMMASTER.SERMGTCOD_0 = 1)
  --- Other PN shoud must with lot
  --OR (ITMMASTER.TSICOD_0 IN ('C0001','C0002','C0003','C0004','C0005','S0001','S0002','S0003') AND ITMMASTER.LOTMGTCOD_0 = 1)